routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ControladorCurso;
use App\Http\Controllers\ControladorNoticia;
use App\Http\Controllers\ControladorPagos;
use App\Http\Controllers\ControladorProfesor;
use App\Http\Controllers\ControladorTemario;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('landing.index');
});

Auth::routes();

Route::get('/register', function () {
    return view('landing.index');
});

Route::get('/allcursos'				, [HomeController::class, 'cursos']);
Route::get('/cursos'				, [HomeController::class, 'cursos']);
Route::get('/curso/{id}'			, [HomeController::class, 'curso']);
Route::get('/blog'					, [HomeController::class, 'blog']);
Route::post('/contacto'				, [HomeController::class, 'contacto']);
Route::post('/info'					, [HomeController::class, 'info']);
Route::post('/buscar'				, [HomeController::class, 'buscar']);

Route::get('/pago/success'			, [HomeController::class, 'pago_success']);
Route::get('/pago/failure'			, [HomeController::class, 'pago_failure']);
Route::get('/pago/pending'			, [HomeController::class, 'pago_pending']);


Route::get('aprobado', function () {
    return view('landing.pago.aprobado');
});
Route::get('rechazado', function () {
    return view('landing.pago.rechazado');
});
Route::get('pendiente', function () {
    return view('landing.pago.pendiente');
});

Route::get('/home'					, [HomeController::class, 'index'])->middleware('auth')->name('home');
Route::resource('admin/cursos' 		, ControladorCurso::class)->middleware('auth');
Route::resource('admin/temario' 	, ControladorTemario::class)->middleware('auth');
Route::resource('admin/noticias' 	, ControladorNoticia::class)->middleware('auth');
Route::resource('admin/pagos' 		, ControladorPagos::class)->middleware('auth');
Route::resource('admin/profesores' 	, ControladorProfesor::class)->middleware('auth');

Route::get('admin/perfil', function () {
    return view('auth.perfil');
});

Route::post('admin/perfil'			, [HomeController::class, 'perfil']);

app/Models/Noticia.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Noticia extends Model
{
    use HasFactory;
}

resources/views/noticias/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-12">
             <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <div class="row">
                        <div class="col-6">
                            <h6 class="m-0 font-weight-bold text-primary">Nueva noticia</h6>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{{url('admin/noticias')}}" class="btn btn-secondary">
                                <i class="fa fa-chevron-left"></i>
                                Atras
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{url('admin/noticias')}}" class="form-horizontal" method="post" enctype="multipart/form-data">
                    	@csrf
                    	<div class="row">
                    		<div class="col-12 col-lg-8">
                    			<div class="form-group">
		                    		<label for="">Titulo</label>
		                    		<input type="text" name="titulo" class="form-control" placeholder="Ingrese el titulo aquí" required="" autofocus="">
		                    	</div>
                    		</div>
                    		<div class="col-12 col-lg-4">
                    			<div class="form-group">
                    				<div class="label">Imagen</div>
                    				<input type="file" name="imagen" class="form-control" required="">
                    			</div>
                    		</div>
                    	</div>
                    	<div class="row">
                    		<div class="col-12">
                    			<label for="">Texto</label>
                    			<textarea name="texto" id="editor" rows="10" class="summernote form-control" required="" ></textarea>
                    		</div>
                    	</div>
                    	<hr>
                    	<div class="row">
                    		<div class="col-12 text-right">
	                    		<button class="btn btn-primary">
	                    			<i class="fa fa-save"></i>
	                    			Guardar
	                    		</button>
                    		</div>
                    	</div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
	<script>
		$('.summernote').summernote({
			  height: 200,   //set editable area's height
			  codemirror: { // codemirror options
			    theme: 'monokai'
			  }
			});
	</script>
@endsection

resources/views/noticias/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-12">
             <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <div class="row">
                        <div class="col-6">
                            <h6 class="m-0 font-weight-bold text-primary">Editar noticia</h6>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{{url('admin/noticias')}}" class="btn btn-secondary">
                                <i class="fa fa-chevron-left"></i>
                                Atras
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{url('admin/noticias', $noticia->id)}}" class="form-horizontal" method="post" enctype="multipart/form-data">
                    	@csrf
                    	@method('PATCH')
                    	<div class="row">
                    		<div class="col-12 col-lg-8">
                    			<div class="form-group">
		                    		<label for="">Titulo</label>
		                    		<input type="text" name="titulo" class="form-control" placeholder="Ingrese el titulo aquí" required="" autofocus="" value="{{$noticia->titulo}}">
		                    	</div>
                    		</div>
                    		<div class="col-12 col-lg-4">
                    			<div class="form-group">
                    				<div class="label">Imagen</div>
                    				<img src="{{asset($noticia->imagen)}}" alt="" width="100px">
                    				<input type="file" name="imagen" class="form-control" >
                    			</div>
                    		</div>
                    	</div>
                    	<div class="row">
                    		<div class="col-12">
                    			<label for="">Texto</label>
                    			<textarea name="texto" id="editor" rows="10" class="summernote form-control" required="" >{{$noticia->texto}}</textarea>
                    		</div>
                    	</div>
                    	<hr>
                    	<div class="row">
                    		<div class="col-12 text-right">
	                    		<button class="btn btn-primary">
	                    			<i class="fa fa-save"></i>
	                    			Guardar
	                    		</button>
                    		</div>
                    	</div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
	<script>
		$('.summernote').summernote({
			  height: 200,   //set editable area's height
			  codemirror: { // codemirror options
			    theme: 'monokai'
			  }
			});
	</script>
@endsection

resources/views/noticias/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-12">
            @include('helps.alert')
             <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <div class="row">
                        <div class="col-6">
                            <h6 class="m-0 font-weight-bold text-primary">Noticias</h6>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{{url('admin/noticias/create')}}" class="btn btn-success">
                                <i class="fa fa-plus"></i>
                                Nueva noticia
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table table-responsive">
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <td>Imagen</td>
                                    <td>titulo</td>
                                    <td>Texto</td>
                                    <td>Fecha</td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                @foreach($noticias as $noticia)
                                    <tr>
                                        <td>
                                            <img src="{{asset($noticia->imagen)}}" alt="" width="100px">
                                        </td>
                                        <td>{{$noticia->titulo}}</td>
                                        <td>{!!$noticia->texto!!}</td>
                                        <td>{{$noticia->created_at->format('d/m/Y H:i')}}</td>
                                        <td>
                                            <a href="{{route('noticias.edit', $noticia->id)}}" class="btn btn-info">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                        </td>
                                        <td>
                                            @include('helps.delete', ['id' => $noticia->id, 'ruta' => url('admin/noticias', $noticia->id)])
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection