routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ControladorCurso;
use App\Http\Controllers\ControladorNoticia;
use App\Http\Controllers\ControladorPagos;
use App\Http\Controllers\ControladorProfesor;
use App\Http\Controllers\ControladorTemario;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('landing.index');
});

Auth::routes();

Route::get('/register', function () {
    return view('landing.index');
});

Route::get('/allcursos'				, [HomeController::class, 'cursos']);
Route::get('/cursos'				, [HomeController::class, 'cursos']);
Route::get('/curso/{id}'			, [HomeController::class, 'curso']);
Route::get('/blog'					, [HomeController::class, 'blog']);
Route::post('/contacto'				, [HomeController::class, 'contacto']);
Route::post('/info'					, [HomeController::class, 'info']);
Route::post('/buscar'				, [HomeController::class, 'buscar']);

Route::get('/pago/success'			, [HomeController::class, 'pago_success']);
Route::get('/pago/failure'			, [HomeController::class, 'pago_failure']);
Route::get('/pago/pending'			, [HomeController::class, 'pago_pending']);


Route::get('aprobado', function () {
    return view('landing.pago.aprobado');
});
Route::get('rechazado', function () {
    return view('landing.pago.rechazado');
});
Route::get('pendiente', function () {
    return view('landing.pago.pendiente');
});

Route::get('/home'					, [HomeController::class, 'index'])->middleware('auth')->name('home');
Route::resource('admin/cursos' 		, ControladorCurso::class)->middleware('auth');
Route::resource('admin/temario' 	, ControladorTemario::class)->middleware('auth');
Route::resource('admin/noticias' 	, ControladorNoticia::class)->middleware('auth');
Route::resource('admin/pagos' 		, ControladorPagos::class)->middleware('auth');
Route::resource('admin/profesores' 	, ControladorProfesor::class)->middleware('auth');

Route::get('admin/perfil', function () {
    return view('auth.perfil');
});

Route::post('admin/perfil'			, [HomeController::class, 'perfil']);

app/Models/Curso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Curso extends Model
{
    use HasFactory;

    function temario()
    {
    	return $this->hasMany('App\Models\Temario', 'curso_id');
    }

    function pagos()
    {
    	return $this->hasMany('App\Models\Pago', 'curso_id');
    }
    
}

resources/views/cursos/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-12">
             <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <div class="row">
                        <div class="col-6">
                            <h6 class="m-0 font-weight-bold text-primary">Nuevo Curso</h6>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{{url('admin/cursos')}}" class="btn btn-secondary">
                                <i class="fa fa-chevron-left"></i>
                                Atras
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{url('admin/cursos')}}" class="form-horizontal" method="post" enctype="multipart/form-data">
                    	@csrf
                    	<div class="row">
                    		<div class="col-12 col-lg-8">
                    			<div class="form-group">
		                    		<label for="">Titulo</label>
		                    		<input type="text" name="titulo" class="form-control" placeholder="Ingrese el titulo aquí" required="" autofocus="">
		                    	</div>
                    		</div>
                    		<div class="col-12 col-lg-4">
                    			<div class="form-group">
                    				<div class="label">Imagen</div>
                    				<input type="file" name="imagen" class="form-control" required="">
                    			</div>
                    		</div>
                    	</div>
                    	<div class="row">
                    		<div class="col-12">
                    			<label for="">Descripción</label>
                    			<textarea name="descripcion" id="editor" rows="10" class="summernote form-control" required="" ></textarea>
                    		</div>
                    	</div>
                    	<br>
                    	<div class="row">
                    		<div class="col-12 col-md-4">
                    			<div class="form-group">
                    				<label for="">Modalidad</label>
                    				<select name="modalidad" id="" class="form-control">
                    					<option value="Prepresencial">Presencial</option>
                    					<option value="Virtual">Virtual</option>
                    				</select>
                    			</div>
                    		</div>
                    		<div class="col-12 col-md-4">
                                <div class="form-group">
                                    <label for="">Carga horaria</label>
                                    <input type="text" name="carga_horaria" class="form-control" placeholder="Horas" required="">
                                </div>
                            </div>
                            <div class="col-12 col-md-4">
                                <div class="form-group">
                                    <label for="">Precio</label>
                                    <input type="number" name="precio" class="form-control" placeholder="precio" >
                                </div>
                            </div>
                    	</div>
                    	<hr>
                    	<div class="row">
                    		<div class="col-12 text-right">
	                    		<button class="btn btn-primary">
	                    			<i class="fa fa-save"></i>
	                    			Guardar
	                    		</button>
                    		</div>
                    	</div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
	<script>
		$('.summernote').summernote({
			  height: 200,   //set editable area's height
			  codemirror: { // codemirror options
			    theme: 'monokai'
			  }
			});
	</script>
@endsection

resources/views/cursos/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-12">
             <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <div class="row">
                        <div class="col-6">
                            <h6 class="m-0 font-weight-bold text-primary">Editar Curso</h6>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{{url('admin/cursos')}}" class="btn btn-secondary">
                                <i class="fa fa-chevron-left"></i>
                                Atras
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{url('admin/cursos', $curso->id)}}" class="form-horizontal" method="post" enctype="multipart/form-data">
                    	@csrf
                    	@method('PATCH')
                    	<div class="row">
                    		<div class="col-12 col-lg-8">
                    			<div class="form-group">
		                    		<label for="">Titulo</label>
		                    		<input type="text" name="titulo" class="form-control" placeholder="Ingrese el titulo aquí" required="" autofocus="" value="{{$curso->titulo}}">
		                    	</div>
                    		</div>
                    		<div class="col-12 col-lg-4">
                    			<div class="form-group">
                    				<div class="label">Imagen</div>
                    				<img src="{{asset($curso->imagen)}}" alt="" width="100px">
                    				<input type="file" name="imagen" class="form-control" value="{{$curso->imagen}}">
                    			</div>
                    		</div>
                    	</div>
                    	<div class="row">
                    		<div class="col-12">
                    			<label for="">Descripción</label>
                    			<textarea name="descripcion" id="editor" rows="10" class="summernote form-control" required="" >{{$curso->descripcion}}</textarea>
                    		</div>
                    	</div>
                    	<br>
                    	<div class="row">
                    		<div class="col-12 col-md-4">
                    			<div class="form-group">
                    				<label for="">Modalidad</label>
                    				<select name="modalidad" id="" class="form-control">
                    					@if($curso->modalidad == "Virtual")
                    						<option value="Prepresencial">Presencial</option>
                    						<option value="Virtual" selected="">Virtual</option>
                    					@else
                    						<option value="Prepresencial" selected="">Presencial</option>
                    						<option value="Virtual">Virtual</option>
                    					@endif
                    				</select>
                    			</div>
                    		</div>
                    		<div class="col-12 col-md-4">
                    			<div class="form-group">
                    				<label for="">Carga horaria</label>
                    				<input type="text" name="carga_horaria" class="form-control" placeholder="Horas" required="" value="{{$curso->carga_horaria}}">
                    			</div>
                    		</div>
                            <div class="col-12 col-md-4">
                                <div class="form-group">
                                    <label for="">Precio</label>
                                    <input type="number" name="precio" class="form-control" value="{{$curso->precio}}">
                                </div>
                            </div>
                    	</div>
                    	<hr>
                    	<div class="row">
                    		<div class="col-12 text-right">
	                    		<button class="btn btn-primary">
	                    			<i class="fa fa-save"></i>
	                    			Guardar
	                    		</button>
                    		</div>
                    	</div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
	<script>
		$('.summernote').summernote({
			  height: 200,   //set editable area's height
			  codemirror: { // codemirror options
			    theme: 'monokai'
			  }
			});
	</script>
@endsection

resources/views/cursos/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-12">
            @include('helps.alert')
             <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <div class="row">
                        <div class="col-6">
                            <h6 class="m-0 font-weight-bold text-primary">Cursos</h6>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{{url('admin/cursos/create')}}" class="btn btn-success">
                                <i class="fa fa-plus"></i>
                                Nuevo curso
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table table-responsive">
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <td>Imagen</td>
                                    <td>Nombre</td>
                                    <td>Pecio</td>
                                    <td>Carga horaria</td>
                                    <td>Temas</td>
                                    <td>Editar</td>
                                    <td>Eliminar</td>
                                </tr>
                                @foreach($cursos as $curso)
                                    <tr>
                                        <td>
                                            <img src="{{asset($curso->imagen)}}" alt="" width="100px">
                                        </td>
                                        <td>{{$curso->titulo}}</td>
                                        <td>${{$curso->precio}}</td>
                                        <td>{{$curso->carga_horaria}}</td>
                                        <td>
                                            <a href="{{url('admin/temario',$curso->id)}}" class="btn btn-primary">
                                                <i class="fa fa-book"></i>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{route('cursos.edit', $curso->id)}}" class="btn btn-info">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                        </td>
                                        <td>
                                            @include('helps.delete', ['id' => $curso->id, 'ruta' => url('admin/cursos', $curso->id)])
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/cursos/temas.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-12">
            @include('helps.alert')
             <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <div class="row">
                        <div class="col-6">
                            <h6 class="m-0 font-weight-bold text-primary">Temas del curso "{{$curso->titulo}}"</h6>
                        </div>
                        <div class="col-6 text-right">
                        	<!-- Button trigger modal -->
							<button type="button" class="btn btn-success" data-toggle="modal" data-target="#addTeme">
								<i class="fa fa-plus"></i>
								Nuevo tema
							</button>

							<!-- Modal -->
							<div class="modal fade" id="addTeme" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true" >
								<div class="modal-dialog" role="document">
							  		<div class="modal-content">
										<div class="modal-header">
							        		<h5 class="modal-title" id="exampleModalLabel">Nuevo tema</h5>

											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
							    		</div>
							    		<div class="modal-body text-left">
							      			<form action="{{url('admin/temario')}}" method="post" class="form-horizontal">
												@csrf
												<input type="hidden" name="curso" value="{{$curso->id}}">
												<div class="form-group">
													<label for="">Titulo</label>
													<input type="text" class="form-control" name="titulo" placeholder="Ingrese el titulo aqui" id="titulo">
												</div>
												<hr>
												<div class="row">
													<div class="col-6">
														<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
													</div>
													<div class="col-6 text-right">
														<button class="btn btn-primary">
															<i class="fa fa-save"></i>
															Guardar
														</button>			
													</div>
												</div>
											</form>
							    		</div>
							  		</div>
								</div>
							</div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table table-responsive">
                        <table class="table table-striped">
                            <tbody>
                                @foreach($temas as $tema)
                                    <tr>
                                        <td>
                                            {{$tema->titulo}}
                                        </td>
                                        <td>
                                        	<button type="button" class="btn btn-success" data-toggle="modal" data-target="#editarTema{{$tema->id}}">
												<i class="fa fa-edit"></i>
											</button>

											<!-- Modal -->
											<div class="modal fade" id="editarTema{{$tema->id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true" >
												<div class="modal-dialog" role="document">
											  		<div class="modal-content">
														<div class="modal-header">
											        		<h5 class="modal-title" id="exampleModalLabel">Editar tema</h5>

															<button type="button" class="close" data-dismiss="modal" aria-label="Close">
																<span aria-hidden="true">&times;</span>
															</button>
											    		</div>
											    		<div class="modal-body text-left">
											      			<form action="{{url('admin/temario', $tema->id)}}" method="post" class="form-horizontal">
																@csrf
																@method('PATCH')
																<div class="form-group">
																	<label for="">Titulo</label>
																	<input type="text" class="form-control" name="titulo" value="{{$tema->titulo}}">
																</div>
																<hr>
																<div class="row">
																	<div class="col-6">
																		<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
																	</div>
																	<div class="col-6 text-right">
																		<button class="btn btn-primary">
																			<i class="fa fa-save"></i>
																			Guardar
																		</button>			
																	</div>
																</div>
															</form>
											    		</div>
											  		</div>
												</div>
											</div>
                                        </td>
                                        <td>
                                            @include('helps.delete', ['id' => $tema->id, 'ruta' => url('admin/temario', $tema->id)])
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    
    <script>
        $('#addTeme').on('shown.bs.modal', function () {
          $('#titulo').trigger('focus')
        })
    </script>
@endsection