routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ControladorCurso;
use App\Http\Controllers\ControladorNoticia;
use App\Http\Controllers\ControladorPagos;
use App\Http\Controllers\ControladorProfesor;
use App\Http\Controllers\ControladorTemario;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('landing.index');
});

Auth::routes();

Route::get('/register', function () {
    return view('landing.index');
});

Route::get('/allcursos'				, [HomeController::class, 'cursos']);
Route::get('/cursos'				, [HomeController::class, 'cursos']);
Route::get('/curso/{id}'			, [HomeController::class, 'curso']);
Route::get('/blog'					, [HomeController::class, 'blog']);
Route::post('/contacto'				, [HomeController::class, 'contacto']);
Route::post('/info'					, [HomeController::class, 'info']);
Route::post('/buscar'				, [HomeController::class, 'buscar']);

Route::get('/pago/success'			, [HomeController::class, 'pago_success']);
Route::get('/pago/failure'			, [HomeController::class, 'pago_failure']);
Route::get('/pago/pending'			, [HomeController::class, 'pago_pending']);


Route::get('aprobado', function () {
    return view('landing.pago.aprobado');
});
Route::get('rechazado', function () {
    return view('landing.pago.rechazado');
});
Route::get('pendiente', function () {
    return view('landing.pago.pendiente');
});

Route::get('/home'					, [HomeController::class, 'index'])->middleware('auth')->name('home');
Route::resource('admin/cursos' 		, ControladorCurso::class)->middleware('auth');
Route::resource('admin/temario' 	, ControladorTemario::class)->middleware('auth');
Route::resource('admin/noticias' 	, ControladorNoticia::class)->middleware('auth');
Route::resource('admin/pagos' 		, ControladorPagos::class)->middleware('auth');
Route::resource('admin/profesores' 	, ControladorProfesor::class)->middleware('auth');

Route::get('admin/perfil', function () {
    return view('auth.perfil');
});

Route::post('admin/perfil'			, [HomeController::class, 'perfil']);

resources/views/profesores/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-12">
             <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <div class="row">
                        <div class="col-6">
                            <h6 class="m-0 font-weight-bold text-primary">Nuevo Profesor</h6>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{{url('admin/profesores')}}" class="btn btn-secondary">
                                <i class="fa fa-chevron-left"></i>
                                Atras
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{url('admin/profesores')}}" class="form-horizontal col-lg-8 offset-lg-2" method="post" enctype="multipart/form-data">
                    	@csrf
	        			<div class="form-group">
	        				<div class="label">Imagen</div>
	        				<input type="file" name="imagen" class="form-control" required="">
	        			</div>

	                	<div class="form-group">
	                		<label for="">Nombre</label>
	                		<input type="text" name="nombre" class="form-control" placeholder="Ingrese el nombre aquí" required="" autofocus="">
	                	</div>
	        		
	        			<div class="form-group">
	        				<div class="label">Especialidad</div>
	        				<input type="text" name="posicion" class="form-control" required="" placeholder="Especialidad">
	        			</div>
	        			<div class="form-group">
	        				<div class="label">Linked in</div>
	        				<input type="text" name="linkedin" class="form-control" placeholder="https://linkedin.com/in/usuario">
	        			</div>

                    	<hr>
                    	<div class="form-group text-right">
	            			<button class="btn btn-primary">
	                			<i class="fa fa-save"></i>
	                			Guardar
	                		</button>
                    	</div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/profesores/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-12">
             <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <div class="row">
                        <div class="col-6">
                            <h6 class="m-0 font-weight-bold text-primary">Editar Profesor</h6>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{{url('admin/profesores')}}" class="btn btn-secondary">
                                <i class="fa fa-chevron-left"></i>
                                Atras
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{url('admin/profesores', $profesor->id)}}" class="form-horizontal col-lg-8 offset-lg-2" method="post" enctype="multipart/form-data">
                    	@csrf
                    	@method('PATCH')
	        			<div class="form-group">
	        				<div class="label">Imagen</div>
	        				<img src="{{asset($profesor->imagen)}}" alt="" width="100px">
	        				<input type="file" name="imagen" class="form-control">
	        			</div>

	                	<div class="form-group">
	                		<label for="">Nombre</label>
	                		<input type="text" name="nombre" class="form-control" value="{{$profesor->nombre}}" required="" autofocus="">
	                	</div>
	        		
	        			<div class="form-group">
	        				<div class="label">Especialidad</div>
	        				<input type="text" name="posicion" class="form-control" required="" value="{{$profesor->posicion}}">
	        			</div>
	        			<div class="form-group">
	        				<div class="label">Linked in</div>
	        				<input type="text" name="linkedin" class="form-control" value="{{$profesor->linkedin}}">
	        			</div>

                    	<hr>
                    	<div class="form-group text-right">
	            			<button class="btn btn-primary">
	                			<i class="fa fa-save"></i>
	                			Guardar
	                		</button>
                    	</div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/profesores/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="row">
        <div class="col-12">
            @include('helps.alert')
             <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <div class="row">
                        <div class="col-6">
                            <h6 class="m-0 font-weight-bold text-primary">Profesores</h6>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{{url('admin/profesores/create')}}" class="btn btn-success">
                                <i class="fa fa-plus"></i>
                                Nuevo profesor
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table table-responsive">
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <td>Imagen</td>
                                    <td>Nombre</td>
                                    <td>Especialidad</td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                @foreach($profesores as $profesor)
                                    <tr>
                                        <td>
                                            <img src="{{asset($profesor->imagen)}}" alt="" width="100px" class="rounded-circle">
                                        </td>
                                        <td>{{$profesor->nombre}}</td>
                                        <td>{{$profesor->posicion}}</td>
                                        <td>
                                            <a href="{{route('profesores.edit', $profesor->id)}}" class="btn btn-info">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                        </td>
                                        <td>
                                            @include('helps.delete', ['id' => $profesor->id, 'ruta' => url('admin/profesores', $profesor->id)])
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection